FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY detection_app ./detection_app
COPY app.py .
COPY .streamlit ./.streamlit
COPY assets ./assets
COPY models ./models
EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]

